name: Build and Push

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write # Required for GHCR push
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: leFooc
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Set image name
        id: metadata
        run: echo "IMAGE_NAME=ghcr.io/lefooc/test" >> $GITHUB_ENV

      - name: Build Docker image
        run: ls && docker build -t $IMAGE_NAME:latest -f ./helloserver/Dockerfile .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest